name: Whitesource Prioritize Java with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: WhiteSource Unified Agent Scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.ref}}_Prioritize
        WS_ENABLEIMPACTANALYSIS: true
        WS_REQUIREKNOWNSHA1: false
        WS_RESOLVEALLDEPENDENCIES: false
        WS_MAVEN_RESOLVEDEPENDENCIES: true
        WS_MAVEN_AGGREGATEMODULES: true
        WS_FILESYSTEMSCAN: false
        WS_GENERATEPROJECTDETAILSJSON: true
      run: |
        curl -LJO https://github.com/k-tamura/easybuggy/releases/download/1.4.0/ROOT.war
        echo Artifact downloaded successfully
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        # replace .war with .jar or .ear if needed
        ARTIFACT=$(find ./ -type f -wholename "*.war")
        java -jar wss-unified-agent.jar -appPath $ARTIFACT -d ./
    - name: 'Upload WhiteSource folder'
      uses: actions/upload-artifact@v2
      with:
        name: Whitesource
        path: whitesource
        retention-days: 1
        
        
